name: Deploy to Server

on:
  push:
    branches:
      - development  # Trigger the workflow when code is pushed to the development branch

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu]  # This ensures the job runs on the self-hosted runner with the 'ubuntu' label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Deploy to server
      run: |
        echo "The runner is live!!!!!!!!"
