name: Deploy to Server

on:
  push:
    branches:
      - development  # Trigger the workflow when code is pushed to the development branch

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu]  # This ensures the job runs on the self-hosted runner with the 'ubuntu' label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # Use the SSH key to authenticate
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Navigate to the project directory on your server
          cd ${{ secrets.SERVER_PATH }}
          
          # Pull the latest changes from the development branch
          git fetch origin
          git checkout development
          git pull origin development
          
          # Optionally, restart your service, e.g., a Node.js app or web server
          # systemctl restart your-app-service
        EOF
